name: my-first-workflow
on:
  push:
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
      - name: Step-2 - Checkout
        uses: actions/checkout@v5.0.0
      - name: Step-3
        run: |
          pwd
          ls -ltr
          hostname
