name: my-first-workflow
on:
  push:
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 - Checkout
        uses: actions/checkout@v5.0.0
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt
          mkdir artifacts
          echo 'ls -ltr' >> artifacts/list.txt
          echo 'hostname' >> artifacts/hostname.txt
      - name: Upload Single file
        uses: actions/upload-artifact@v5.0.0
        with:
          name: single_file
          path: ./myartifact.txt
      - name: Upload from directory
        uses: actions/upload-artifact@v5.0.0
        with:
          name: directory_artifacts
          path: artifacts/
      - name: Upload from multiple paths with exclusions
        uses: actions/upload-artifact@v5.0.0
        with:
          name: multiple_paths_with_exclusions
          path: |
            ./myartifact.txt
            artifacts/
            !**/hostname.txt

  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking current directory
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: single_file
      - name: Checking current directory post download
        run: |
          pwd
          ls -ltr
